basePath: /
definitions:
  models.CreateOrderRequest:
    properties:
      order:
        $ref: '#/definitions/models.Order'
      seat_ids:
        items:
          type: integer
        type: array
    type: object
  models.LoginRequest:
    properties:
      email:
        example: user@mail.com
        type: string
      password:
        example: "123456"
        type: string
    required:
    - email
    - password
    type: object
  models.Order:
    properties:
      created_at:
        type: string
      email:
        example: johndoe@mail.com
        type: string
      fullname:
        example: John Doe
        type: string
      id:
        type: integer
      payment_id:
        example: 2
        type: integer
      phone:
        example: "08123456789"
        type: string
      qr_code:
        type: string
      schedule_id:
        example: 10
        type: integer
      seats:
        items:
          $ref: '#/definitions/models.Seat'
        type: array
      updated_at:
        type: string
      user_id:
        example: 1
        type: integer
    type: object
  models.Profile:
    properties:
      firstname:
        example: Farid
        type: string
      lastname:
        example: Darari
        type: string
      phone_number:
        example: "089876543210"
        type: string
      user_id:
        example: 1
        type: integer
    type: object
  models.RegisterRequest:
    properties:
      email:
        example: newuser@mail.com
        type: string
      firstname:
        example: John
        type: string
      lastname:
        example: Doe
        type: string
      password:
        example: mypassword
        type: string
      phone_number:
        example: "08123456789"
        type: string
      role:
        example: user
        type: string
    required:
    - email
    - password
    type: object
  models.Seat:
    properties:
      id:
        type: integer
      seat_code:
        type: string
    type: object
  models.UpdateMovieRequest:
    properties:
      backdrop:
        example: https://image.tmdb.org/t/p/w500/backdrop.jpg
        type: string
      director:
        example: Anthony Russo, Joe Russo
        type: string
      duration:
        example: 180
        type: integer
      overview:
        example: After the devastating events of Infinity War...
        type: string
      popularity:
        example: 95.6
        type: number
      poster:
        example: https://image.tmdb.org/t/p/w500/poster.jpg
        type: string
      release_date:
        example: "2019-04-26T00:00:00Z"
        type: string
      title:
        example: 'Avengers: Endgame'
        type: string
    required:
    - backdrop
    - director
    - duration
    - overview
    - popularity
    - poster
    - release_date
    - title
    type: object
host: localhost:8080
info:
  contact: {}
  description: RESTful API created using gin for BE GO Tickitz App
  title: Backend Golang Tickitz App
  version: "1.0"
paths:
  /admin/movies:
    get:
      description: Semua data Movie untuk admin
      produces:
      - application/json
      responses:
        "200":
          description: List of all movies
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to fetch movies
          schema:
            additionalProperties: true
            type: object
      summary: Get All Movies (Admin)
      tags:
      - Admin-Movies
  /admin/movies/{id}:
    delete:
      description: Hapus movie berdasarkan ID
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Movie deleted
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid movie ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to delete movie
          schema:
            additionalProperties: true
            type: object
      summary: Delete Movie (Admin)
      tags:
      - Admin-Movies
    put:
      consumes:
      - application/json
      description: Update data movie berdasarkan ID
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: integer
      - description: Movie Update Data
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/models.UpdateMovieRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Movie updated
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to update movie
          schema:
            additionalProperties: true
            type: object
      summary: Update Movie (Admin)
      tags:
      - Admin-Movies
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login dengan email dan password, JWT disini
      parameters:
      - description: Login Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login berhasil, berisi token dan data user
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Invalid email atau password
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to generate token
          schema:
            additionalProperties: true
            type: object
      summary: Login User
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Daftar User baru beserta profile
      parameters:
      - description: Register Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Register berhasil
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties: true
            type: object
        "409":
          description: Email already exists
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to create user or profile
          schema:
            additionalProperties: true
            type: object
      summary: Register User
      tags:
      - Auth
  /movies:
    get:
      description: 'Movie lists pagination (default limit: 10, offset: 0)'
      parameters:
      - description: 'Jumlah data per halaman (Default: 10)'
        in: query
        name: limit
        type: integer
      - description: 'Offset data (Default: 0)'
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of movies with pagination
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to fetch movies
          schema:
            additionalProperties: true
            type: object
      summary: Get Movies with Pagination
      tags:
      - Movies
  /movies/{id}:
    get:
      description: Detail lengkap movie berdasarkan ID
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Movie detail
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid movie ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Movie not found
          schema:
            additionalProperties: true
            type: object
      summary: Get Movie Detail
      tags:
      - Movies
  /movies/{id}/schedules:
    get:
      description: Get Schedule by Movie ID
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of schedules
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid movie ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to fetch schedule
          schema:
            additionalProperties: true
            type: object
      summary: Get Schedule by Movie ID
      tags:
      - Movies
  /movies/popular:
    get:
      description: Popular Movies
      produces:
      - application/json
      responses:
        "200":
          description: List of popular movies
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to fetch popular movies
          schema:
            additionalProperties: true
            type: object
      summary: Get Popular Movies
      tags:
      - Movies
  /movies/schedules/{schedule_id}/seats:
    get:
      description: kursi kosong berdasarkan schedule ID
      parameters:
      - description: Schedule ID
        in: path
        name: schedule_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of available seats
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid schedule ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to fetch available seats
          schema:
            additionalProperties: true
            type: object
      summary: Get Available Seats
      tags:
      - Movies
  /movies/upcoming:
    get:
      description: Upcoming Movies
      produces:
      - application/json
      responses:
        "200":
          description: List of upcoming movies
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to fetch upcoming movies
          schema:
            additionalProperties: true
            type: object
      summary: Get Upcoming Movies
      tags:
      - Movies
  /orders:
    post:
      consumes:
      - application/json
      description: Buat pesanan baru
      parameters:
      - description: Order Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Order created with details
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to create order
          schema:
            additionalProperties: true
            type: object
      summary: Create a new Order
      tags:
      - Orders
  /orders/{id}:
    get:
      description: Detail pesanan berdasarkan Order ID
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Order detail
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid order ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Order not found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to fetch order
          schema:
            additionalProperties: true
            type: object
      summary: Get Order Detail
      tags:
      - Orders
  /orders/user/{user_id}:
    get:
      description: Semua order milik user berdasarkan User ID
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of orders
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid user ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: No orders found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to fetch orders
          schema:
            additionalProperties: true
            type: object
      summary: Get Order History by User
      tags:
      - Orders
  /profile:
    get:
      description: Data profil user login
      produces:
      - application/json
      responses:
        "200":
          description: Get Profile Success
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Profile not found
          schema:
            additionalProperties: true
            type: object
      summary: Get User Profile
      tags:
      - Profile
    put:
      consumes:
      - application/json
      description: Update data profil user yang sedang login
      parameters:
      - description: Profile data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Profile'
      produces:
      - application/json
      responses:
        "200":
          description: Profile updated
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to update profile
          schema:
            additionalProperties: true
            type: object
      summary: Update User Profile
      tags:
      - Profile
swagger: "2.0"
